In [4]:
#1
import numpy as n
a=[1,2,3,4]
b=n.array(a)
print(b[3])

4


In [7]:
#2
import numpy as lx
z=lx.zeros(5, dtype=int)
print(z)

[0 0 0 0 0]


In [8]:
#3
import numpy as lx
z=lx.ones(5, dtype=int)
print(z)

[1 1 1 1 1]


In [9]:
#4
import numpy as lx
z=lx.empty(2)
print(z)

[4.24399158e-314 8.48798317e-314]


In [10]:
#5
import numpy as lx
z=lx.arange(2,7)
print(z)

[2 3 4 5 6]
