# Name: Laxita Jain Roll No.:E202 B.Tech. C.S. (A) BATCH: A1 EXP5

In [3]:
#1
import numpy as np
from numpy import random
x=random.randint(100)
print(x)

70


In [1]:
#2
import numpy as np
l=[]
n=int(input("Enter the size of array: "))
print("Enter the elements: ")
for i in range(n):
    c=int(input())
    l.append(c)
a=np.array(l)
print("The entered array is: ",a)

Enter the size of array: 5
Enter the elements: 
1
21
2
3
4
The entered array is:  [ 1 21  2  3  4]


In [5]:
#3
import numpy as np
l=[]
p=int(input("Enter the number of rows: "))
q=int(input("Enter the number of columns: "))
print("Enter the elements: ")
for i in range(p):
    i=[]
    for j in range(q):
        i.append(int(input()))
    l.append(i)
arr=np.array(l)
print("The entered array is: ")
for i in range(p):
    for j in range(q):
        print(arr[i][j],end=" ")
    print()

Enter the number of rows: 2
Enter the number of columns: 2
Enter the elements: 
1
2
3
4
The entered array is: 
1 2 
3 4 


In [14]:
#4
import numpy as np
from numpy import random
l=[]
m=int(input("Enter the number of rows: "))
n=int(input("Enter the number of columns: "))
p=int(input("Enter the start of the range: "))
q=int(input("Enter the end of the range: "))
x=random.randint(p,q,size=(m,n))
print(x)

Enter the number of rows: 2
Enter the number of columns: 2
Enter the start of the range: 34
Enter the end of the range: 40
[[35 35]
 [36 39]]


In [19]:
#5
print("The shape of the above array is: ",x.shape)
print("The size of the above array is: ",x.size)
print("The dimension of the above array is: ",x.ndim)
print("The item-size of the above array is: ",x.itemsize)

The shape of tha above array is:  (2, 2)
The size of the above array is:  4
The dimension of the above array is:  2
The item-size of the above array is:  4


In [6]:
#6
import numpy as np
arr=np.array([[1,2,2,3],[2,3,4,5]])
p=int(input("Enter the reshape row dimension: "))
q=int(input("Enter the reshape column dimension: "))
if p*q!=arr.size:
    print("Invalid dimensions!")
else:
    newarr=arr.reshape(p,q)
    print("The reshaped array is:\n ",newarr)

Enter the reshape row dimension: 4
Enter the reshape column dimension: 2
The reshaped array is:
  [[1 2]
 [2 3]
 [2 3]
 [4 5]]


In [7]:
#7
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print("Sliced 1D array: ",arr1[:3])
print("Sliced 2D array:\n ",arr2[0:2,1:3])

Sliced 1D array:  [1 2 3]
Sliced 2D array:
  [[2 3]
 [6 7]]


In [30]:
#8
import numpy as np
arr1=np.array([99,21,3,30,40])
print("The sorted array is: ",np.sort(arr1))

The sorted array is:  [ 3 21 30 40 99]


In [12]:
#9
import numpy as np
arr=np.array([[81,40],[8,7]])
print("Original array: ",arr)
print("Array sorted along the first axis: ",np.sort(arr,axis=0))
print("Array sorted along the last axis: ",np.sort(arr))
print("Sorted flattened array: ",np.sort(arr,axis=None))


Original array:  [[81 40]
 [ 8  7]]
Array sorted along the first axis:  [[ 8  7]
 [81 40]]
Array sorted along the last axis:  [[40 81]
 [ 7  8]]
Sorted flattened array:  [ 7  8 40 81]
