<a href="https://colab.research.google.com/github/laxitajain/python/blob/main/numpy_all_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [2]:
t=[1,2,3]
ar1=np.array(t)
print(ar1)

[1 2 3]


In [4]:
zerod=np.array(2)
print(oned)
print(type(oned))

2
<class 'numpy.ndarray'>


In [11]:
zerodd=np.array(3, dtype=np.float64)
# or use np.array(3,dtype=float) , but not np.array(3, dtype=np.float)
print(zerodd)

3.0


In [13]:
onedd=np.array([1,23,4])
print(onedd)
twodd=np.array([[1,2,3],[1,2,3]])
print(twodd)
print(twodd.ndim)
print(onedd.ndim)
print(zerodd.ndim)


[ 1 23  4]
[[1 2 3]
 [1 2 3]]
2
1
0


In [14]:
customd=np.array([1,2,3,4],ndmin=5)
print(customd)  #dimension= no. of opening brackets or no. of closing brackets

[[[[[1 2 3 4]]]]]


In [16]:
a=2
customd2=np.array(a,ndmin=1)
print(customd2)

[2]


In [17]:
a=np.array([1,2,3,4])
print(a[2])

3


In [20]:
lst=[[1,2,3],[4,5,6]]
b=np.array(lst)
print(b[1,1])

5


In [24]:
print(b[-1,1])
print(b[-1,-1])
print(b[-2,0])

5
6
1


In [32]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a)  # a 3-d array has 3 params: no. of 2-d arrays, no. of rows, no. of columns
_3d = np.zeros((2, 3, 2))
print(_3d)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [34]:
another_3d=np.ones((2,3,1))
print(another_3d)

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


In [35]:
yet_another_3d=np.ones((1,3,2))
print(yet_another_3d)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [37]:
_2d=np.zeros((2,3))
# a 2-d array has 2 params: no. of rows (or) no. of 1-d arrays, no. of columns
print(_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [38]:
_1d=np.ones((5))
print(_1d)

[1. 1. 1. 1. 1.]


In [41]:
_0d=np.zeros(()) # to create a 0-d array, pass just a '()' as an argument
print(_0d)

0


In [42]:
# default type for ones and zeros creation => np.float64, change it by => dtype = np.int32
_0d=np.ones((),dtype=np.int32)
print(_0d)

1


In [43]:
ar=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar[1:,:3]) # sliced values will be return as an array of the the dimesion of the original array. since two slices are passed.

[[6 7 8]]


In [49]:
ar=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar[:1,2])
print(ar[1,3:5])
print(ar[1])
print(ar[1:,::2])

[3]
[ 9 10]
[ 6  7  8  9 10]
[[ 6  8 10]]


In [64]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print()
print(ar[::2])
print()
print(ar[1:3,:3:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]

[[4 6]
 [7 9]]


In [63]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar[-1:1:-1]) # no negative step required in negative indexing, but a negative step is must in negative slicing, if going from end to start!!
print()
print(ar[-2:-1]) # no negative step required if going from start to end
print()
# however,
print(ar[-2:0]) #shall produce an empty o/p. beacuse we're going from back to start and have the default positive step of 1

[[7 8 9]]

[[4 5 6]]

[]


In [71]:
arr=np.array([7,4,5],dtype=float) #can either use np.float64 or simply float, np.int32 or simply int
print(arr)
print(arr.dtype)

[7. 4. 5.]
float64


In [76]:
arrs=np.array([1,2,3],dtype='S')
print(arrs)
print(arrs.dtype)
print(type(arrs))

print()

arrf=np.array([1,2,3], dtype = 'f')
print(arrf)
print(arrf.dtype)
print(type(arrf))
print()
print(arrf.astype(int))

[b'1' b'2' b'3']
|S1
<class 'numpy.ndarray'>

[1. 2. 3.]
float32
<class 'numpy.ndarray'>

[1 2 3]


In [79]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view() #copy is a new array and view is just a view of the orginal array. any changes made to original array won't affect copy and vice-versa, changes made on either one of view or ori. array affect e/o
arr[2]=745
print(arr)
print(x)
print(y)

[  1   2 745   4   5]
[1 2 3 4 5]
[  1   2 745   4   5]


In [86]:
ar=np.array([[1,2,4],[3,4,5]])
print(ar.shape)
print(ar.reshape(3,2)) # for reshaping, size must be equal
print(ar.reshape(6,1))
print(ar.reshape(1,6))

(2, 3)
[[1 2]
 [4 3]
 [4 5]]
[[1]
 [2]
 [4]
 [3]
 [4]
 [5]]
[[1 2 4 3 4 5]]


In [87]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar.reshape(2,2,3)) # the reshape attribute returns a view

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [89]:
ar=np.array([[1,2,4],[3,4,5]])
print(ar.reshape(-1)) #flattening an array
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar.reshape(-1))

[1 2 4 3 4 5]
[1 2 3 4 5 6 7 8 9]


In [97]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in ar:
  print(x)
print()
for x in ar:
  for y in x:
    print(y, end=" ")
print()
for x in np.nditer(ar):
  print(x,end=' ')
print()
for i in np.nditer(ar[:,::2]):
  print(i, end=' ')
print()
for i in np.nditer(ar[::2]):
  print(i, end=' ')


[1 2 3]
[4 5 6]
[7 8 9]

1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 
1 3 4 6 7 9 
1 2 3 7 8 9 

In [104]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
for indx, i in np.ndenumerate(ar):
  print(indx, i)
# the first part of the np.ndenumerate is the index, and second the , for multi-dimensional arrays, the returned index is a tuple



(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [106]:
ar=np.array([1,2,3,4])
ar1=np.array([5,6,7,8,9])
arr=np.concatenate((ar,ar1))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [113]:
ar=np.array([[1,2,3],[4,5,6]])
ar1=np.array([[7,8,9],[10,11,12]])
print(np.concatenate((ar,ar1)))
print()
print(np.concatenate((ar,ar1),axis=1))
#1 => horizontal (along rows) , 0 => vertical (along columns)
print()
print(np.concatenate((ar,ar1),axis=0))
#default axis => 0 (along colums concatenation)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [122]:
ar=np.array([1,2,3])
ar1=np.array([7,8,9])
print(np.stack((ar,ar1))) #default axis => 0
print(np.stack((ar,ar1),axis=1)) #stacking along height (depth)

[[1 2 3]
 [7 8 9]]
[[1 7]
 [2 8]
 [3 9]]


In [118]:
# or to stack along rows: use hstack (horizontal stacking)
print(np.hstack((ar,ar1)))
# or to stack along colums: use vstack (vertical stacking)
print(np.vstack((ar,ar1)))
# or to stack along height
print(np.dstack((ar,ar1)))

[1 2 3 7 8 9]
[[1 2 3]
 [7 8 9]]
[[[1 7]
  [2 8]
  [3 9]]]


In [127]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))
arr2=np.array([1,2,3,4,5])
print(np.array_split(arr2,3))

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5])]
[array([1, 2]), array([3, 4]), array([5])]


In [131]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(np.hsplit(ar,3))
print(np.vsplit(ar,3))

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [138]:
ar=np.array([1,56,2,3,4,5,6])
x=np.searchsorted(ar,2)
print(x)
y=np.searchsorted(ar,56)
print(y)
z=np.searchsorted(ar,6)
print(z)

1
7
6


In [139]:
arr=np.array([3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[0 1 2]


In [141]:
ar=np.array([1,56,2,3,4,5,6])
print(np.sort(ar))

[ 1  2  3  4  5  6 56]


In [142]:
arr=np.array([[7,4,9],[21,9,5]])
print(np.sort(arr))

[[ 4  7  9]
 [ 5  9 21]]


In [146]:
arr=np.array([7,4,9,22])
x=np.where(arr==7)
print(x)
y=np.where(arr%2==0)
print(y)

(array([0]),)
(array([1, 3]),)


In [149]:
arr=np.array([1,2,3,4])
filter=[]
for i in arr:
  if i%2==0:
    filter.append(i)
newarr=np.array(filter)
print(newarr)
filter1= arr>2
print(np.array(filter1))

[2 4]
[False False  True  True]


In [159]:
from numpy import random
x=random.randint(100)
print(x)
y=random.rand()
print(y)
print(random.randint((100),size=5))
print(random.randint((100),size=(2,3)))

88
0.6768938406775017
[48 69 91 91 28]
[[28 98 92]
 [85 79 10]]
