<a href="https://colab.research.google.com/github/laxitajain/python/blob/main/prac5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
n=int(input("Enter the number of elements you wish to enter: "))
print("Enter the elements: ")
l=[]
for i in range(n):
  c=int(input())
  l.append(c)
ar=np.array(l)
print(ar)

Enter the number of elements you wish to enter: 5
Enter the elements: 
1
2
3
6
21
[ 1  2  3  6 21]


In [7]:
import numpy as np
m=int(input("Enter the number of rows: "))
n=int(input("Enter the number of columns: "))
print("Enter the elements: ")
l=[]
for i in range(m):
  i=[]
  for j in range(n):
    i.append(int(input()))
  l.append(i)
ar=np.array(l)
print(ar)

Enter the number of rows: 2
Enter the number of columns: 3
Enter the elements: 
2
1
3
4
5
6
[[2 1 3]
 [4 5 6]]


In [8]:
import numpy as np
m=int(input())
n=int(input())
l=[]
for i in range(m):
  i=[]
  for j in range(n):
    i.append(int(input()))
  l.append(i)
ar=np.array(l)
print(ar)

2
3
1
2
3
21
7
9
[[ 1  2  3]
 [21  7  9]]


In [14]:
print(ar.shape)
print(ar.size)
print(ar.ndim)
print(ar.dtype)
print(ar.itemsize)
print(ar.data)

(2, 3)
6
2
int64
8


In [16]:
m=int(input("Enter the no. of rows: "))
n=int(input("Enter the no. of columns: "))
p=int(input())
q=int(input())
import numpy as np
from numpy import random
newarr=random.randint(p,q,size=(m,n))
print(newarr)

Enter the no. of rows: 2
Enter the no. of columns: 3
50
100
[[59 92 96]
 [75 65 78]]


In [17]:
arr=[1,2,3,4]
a=np.array(arr)
print(a[2:])
arr2=[[1,2,3],[4,5,6]]
b=np.array(arr2)
print(b[1:,:2])

[3 4]
[[4 5]]


In [20]:
p=int(input())
q=int(input())
if p*q!=a.size:
  print("Invalid reshape commands")
else:
  print(a.reshape(p,q))


2
2
[[1 2]
 [3 4]]


In [24]:
a=np.array([7,4,9])
a=np.sort(a)
print(a)

[4 7 9]


In [30]:
a=np.array([[21,9],[7,4]])
print(np.sort(a,axis=0))
print(np.sort(a))
print(np.sort(a,axis=None))

[[ 7  4]
 [21  9]]
[[ 9 21]
 [ 4  7]]
[[ 9 21]
 [ 4  7]]
[ 4  7  9 21]


In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.add(a,b))

[5 7 9]
[ 4 10 18]
[1 2 3]


In [40]:
a=np.array([[4,5,6],[7,8,9],[10,11,12]])
print(np.transpose(a))
print(np.linalg.inv(a))
print(a.T)

[[ 4  7 10]
 [ 5  8 11]
 [ 6  9 12]]
[[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]
[[ 4  7 10]
 [ 5  8 11]
 [ 6  9 12]]


In [42]:
a=np.array([1,2,3])
print(a*2)
b=np.array([[1,2,3],[4,5,6]])
print(b*2)

[2 4 6]
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
a=np.array[[1,2],[3,4]]
b=np.array[[1,2]]
for n in a:
  i=[]
  for j in b:
    i.append()